/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ensambladoresproyecto3;

import com.formdev.flatlaf.FlatIntelliJLaf;
import compilerTools.Directory;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.awt.Image;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;

/**
 *
 * @author Luis Angel Rocha
 */
public class ConversorUnidades extends javax.swing.JFrame {

    private String titulo;
    
    int numerouno,numerodos;
    String signo;
    /**
     * Creates new form AcercaDe
     */
    public ConversorUnidades() {
        initComponents();
        init();
    }
    
    
    public void ConvDecimalBinario(){
        String numerodecimal = txtDecBin.getText();

       int numdecint = Integer.parseInt(numerodecimal);
       
       String numerobin = Integer.toBinaryString(numdecint);
        
        txtResDecBin.setText(numerobin);
    }
    
    public void ConvDecimalHexadecimal(){
        
        String numerodec = txtDecHex.getText();
        int numdec = Integer.parseInt(numerodec);
        
        char digitosH[]={'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F'};
        String hexadecimal = "";
        int resto, aux = numdec;
         
        while(aux>0){
            resto = aux % 16;
            hexadecimal = digitosH[resto] + hexadecimal;
            aux /= 16; 
        }
         
         txtResDecHex.setText(hexadecimal);
        
    }
    
    
    public void ConvHexadecimalDecimal(){
        
        String numhexadecimal = txtHexDec.getText();
        
        int numdecimal = Integer.parseInt(numhexadecimal,16);
        
        String numerohex =  Integer.toString(numdecimal);
        
        txtResHexDec.setText(numerohex);
    }

    public void init(){
         setLocationRelativeTo(null);
         this.setResizable(false);
       // TextPaneCodigoFuente.setEditable(false);
        titulo = "ANALIZADOR LEXICOGRAFICO [CONVERSOR DE UNIDADES]";
        //mostrar ventana en centro de la pantalla
        setLocationRelativeTo(null);
        //concatenar titulo a la ventana
        setTitle(titulo);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("code.png")));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Acercade = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        etiuno = new javax.swing.JPanel();
        btnLimHexDec = new javax.swing.JButton();
        txtResHexDec = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        btnConvHexDec = new javax.swing.JButton();
        txtHexDec = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtDecBin = new javax.swing.JTextField();
        txtResDecBin = new javax.swing.JTextField();
        btbConvDecBin = new javax.swing.JButton();
        btnLimDecBin = new javax.swing.JButton();
        jPanel25 = new javax.swing.JPanel();
        txtDecHex = new javax.swing.JTextField();
        txtResDecHex = new javax.swing.JTextField();
        btnConvDecHex = new javax.swing.JButton();
        btnLimDecHex = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        etiuno1 = new javax.swing.JPanel();
        etiuno2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Acercade.setBackground(new java.awt.Color(32, 33, 36));
        Acercade.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(32, 33, 36));
        jPanel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 222, 222), 2, true));

        jLabel10.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(74, 222, 222));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("CONVERSOR DE UNIDADES");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Acercade.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 30));

        jPanel12.setBackground(new java.awt.Color(74, 222, 222));
        jPanel12.setPreferredSize(new java.awt.Dimension(3, 0));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Acercade.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 950, 10));

        etiuno.setBackground(new java.awt.Color(74, 222, 222));
        etiuno.setPreferredSize(new java.awt.Dimension(3, 0));

        javax.swing.GroupLayout etiunoLayout = new javax.swing.GroupLayout(etiuno);
        etiuno.setLayout(etiunoLayout);
        etiunoLayout.setHorizontalGroup(
            etiunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        etiunoLayout.setVerticalGroup(
            etiunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Acercade.add(etiuno, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 10, 520));

        btnLimHexDec.setBackground(new java.awt.Color(74, 222, 222));
        btnLimHexDec.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnLimHexDec.setForeground(new java.awt.Color(32, 33, 36));
        btnLimHexDec.setText("LIMPIAR");
        btnLimHexDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimHexDecActionPerformed(evt);
            }
        });
        Acercade.add(btnLimHexDec, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 100, -1));

        txtResHexDec.setBackground(new java.awt.Color(60, 64, 67));
        txtResHexDec.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        txtResHexDec.setForeground(new java.awt.Color(74, 222, 222));
        txtResHexDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResHexDecActionPerformed(evt);
            }
        });
        Acercade.add(txtResHexDec, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 240, -1));

        jPanel13.setBackground(new java.awt.Color(74, 222, 222));
        jPanel13.setPreferredSize(new java.awt.Dimension(3, 0));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Acercade.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 410, 10));

        btnConvHexDec.setBackground(new java.awt.Color(74, 222, 222));
        btnConvHexDec.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnConvHexDec.setForeground(new java.awt.Color(32, 33, 36));
        btnConvHexDec.setText("CONVERTIR");
        btnConvHexDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvHexDecActionPerformed(evt);
            }
        });
        Acercade.add(btnConvHexDec, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, -1, -1));

        txtHexDec.setBackground(new java.awt.Color(60, 64, 67));
        txtHexDec.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        txtHexDec.setForeground(new java.awt.Color(74, 222, 222));
        txtHexDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHexDecActionPerformed(evt);
            }
        });
        Acercade.add(txtHexDec, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 240, -1));

        jPanel15.setBackground(new java.awt.Color(32, 33, 36));
        jPanel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 222, 222), 2, true));

        jLabel15.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(74, 222, 222));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("DECIMAL A BINARIO");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
        );

        Acercade.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 210, 30));

        jPanel16.setBackground(new java.awt.Color(32, 33, 36));
        jPanel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 222, 222), 2, true));

        jLabel19.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(74, 222, 222));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("DECIMAL A HEXADECIMAL");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        Acercade.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 210, 30));

        jPanel24.setBackground(new java.awt.Color(32, 33, 36));
        jPanel24.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 222, 222), 2, true));

        jLabel11.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(74, 222, 222));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("HEXADECIMAL A DECIMAL");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Acercade.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 210, 30));

        txtDecBin.setBackground(new java.awt.Color(60, 64, 67));
        txtDecBin.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        txtDecBin.setForeground(new java.awt.Color(74, 222, 222));
        txtDecBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDecBinActionPerformed(evt);
            }
        });
        Acercade.add(txtDecBin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 240, -1));

        txtResDecBin.setBackground(new java.awt.Color(60, 64, 67));
        txtResDecBin.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        txtResDecBin.setForeground(new java.awt.Color(74, 222, 222));
        txtResDecBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResDecBinActionPerformed(evt);
            }
        });
        Acercade.add(txtResDecBin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 240, -1));

        btbConvDecBin.setBackground(new java.awt.Color(74, 222, 222));
        btbConvDecBin.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btbConvDecBin.setForeground(new java.awt.Color(32, 33, 36));
        btbConvDecBin.setText("CONVERTIR");
        btbConvDecBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbConvDecBinActionPerformed(evt);
            }
        });
        Acercade.add(btbConvDecBin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        btnLimDecBin.setBackground(new java.awt.Color(74, 222, 222));
        btnLimDecBin.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnLimDecBin.setForeground(new java.awt.Color(32, 33, 36));
        btnLimDecBin.setText("LIMPIAR");
        btnLimDecBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimDecBinActionPerformed(evt);
            }
        });
        Acercade.add(btnLimDecBin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 100, -1));

        jPanel25.setBackground(new java.awt.Color(74, 222, 222));
        jPanel25.setPreferredSize(new java.awt.Dimension(3, 0));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Acercade.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 410, 10));

        txtDecHex.setBackground(new java.awt.Color(60, 64, 67));
        txtDecHex.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        txtDecHex.setForeground(new java.awt.Color(74, 222, 222));
        txtDecHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDecHexActionPerformed(evt);
            }
        });
        Acercade.add(txtDecHex, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 240, -1));

        txtResDecHex.setBackground(new java.awt.Color(60, 64, 67));
        txtResDecHex.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        txtResDecHex.setForeground(new java.awt.Color(74, 222, 222));
        txtResDecHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResDecHexActionPerformed(evt);
            }
        });
        Acercade.add(txtResDecHex, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 240, -1));

        btnConvDecHex.setBackground(new java.awt.Color(74, 222, 222));
        btnConvDecHex.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnConvDecHex.setForeground(new java.awt.Color(32, 33, 36));
        btnConvDecHex.setText("CONVERTIR");
        btnConvDecHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvDecHexActionPerformed(evt);
            }
        });
        Acercade.add(btnConvDecHex, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        btnLimDecHex.setBackground(new java.awt.Color(74, 222, 222));
        btnLimDecHex.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnLimDecHex.setForeground(new java.awt.Color(32, 33, 36));
        btnLimDecHex.setText("LIMPIAR");
        btnLimDecHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimDecHexActionPerformed(evt);
            }
        });
        Acercade.add(btnLimDecHex, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 100, -1));

        jPanel17.setBackground(new java.awt.Color(74, 222, 222));
        jPanel17.setPreferredSize(new java.awt.Dimension(3, 0));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Acercade.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 950, 10));

        etiuno1.setBackground(new java.awt.Color(74, 222, 222));
        etiuno1.setPreferredSize(new java.awt.Dimension(3, 0));

        javax.swing.GroupLayout etiuno1Layout = new javax.swing.GroupLayout(etiuno1);
        etiuno1.setLayout(etiuno1Layout);
        etiuno1Layout.setHorizontalGroup(
            etiuno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        etiuno1Layout.setVerticalGroup(
            etiuno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Acercade.add(etiuno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 70, 10, 520));

        etiuno2.setBackground(new java.awt.Color(74, 222, 222));
        etiuno2.setPreferredSize(new java.awt.Dimension(3, 0));

        javax.swing.GroupLayout etiuno2Layout = new javax.swing.GroupLayout(etiuno2);
        etiuno2.setLayout(etiuno2Layout);
        etiuno2Layout.setHorizontalGroup(
            etiuno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        etiuno2Layout.setVerticalGroup(
            etiuno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Acercade.add(etiuno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 10, 520));

        jLabel1.setBackground(new java.awt.Color(60, 64, 67));
        jLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(74, 222, 222));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 222, 222), 3, true));
        jLabel1.setOpaque(true);
        Acercade.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 350, 60));

        jButton1.setBackground(new java.awt.Color(60, 64, 67));
        jButton1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(74, 222, 222));
        jButton1.setText("-");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 222, 222), 3, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Acercade.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 80, 60));

        jButton2.setBackground(new java.awt.Color(60, 64, 67));
        jButton2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(74, 222, 222));
        jButton2.setText("=");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 222, 222), 3, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Acercade.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 80, 130));

        jButton3.setBackground(new java.awt.Color(60, 64, 67));
        jButton3.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(74, 222, 222));
        jButton3.setText("/");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 222, 222), 3, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Acercade.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 80, 60));

        jButton4.setBackground(new java.awt.Color(60, 64, 67));
        jButton4.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(74, 222, 222));
        jButton4.setText("X");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 222, 222), 3, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Acercade.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 80, 60));

        jButton5.setBackground(new java.awt.Color(60, 64, 67));
        jButton5.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(74, 222, 222));
        jButton5.setText("C");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 222, 222), 3, true));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Acercade.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 80, 60));

        jButton6.setBackground(new java.awt.Color(60, 64, 67));
        jButton6.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(74, 222, 222));
        jButton6.setText("7");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 222, 222), 3, true));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Acercade.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 80, 60));

        jButton7.setBackground(new java.awt.Color(60, 64, 67));
        jButton7.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(74, 222, 222));
        jButton7.setText("8");
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 222, 222), 3, true));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        Acercade.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 80, 60));

        jButton8.setBackground(new java.awt.Color(60, 64, 67));
        jButton8.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(74, 222, 222));
        jButton8.setText("9");
        jButton8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 222, 222), 3, true));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        Acercade.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 80, 60));

        jButton9.setBackground(new java.awt.Color(60, 64, 67));
        jButton9.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(74, 222, 222));
        jButton9.setText("+");
        jButton9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 222, 222), 3, true));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        Acercade.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 80, 130));

        jButton10.setBackground(new java.awt.Color(60, 64, 67));
        jButton10.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(74, 222, 222));
        jButton10.setText("4");
        jButton10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 222, 222), 3, true));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        Acercade.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 80, 60));

        jButton11.setBackground(new java.awt.Color(60, 64, 67));
        jButton11.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(74, 222, 222));
        jButton11.setText("5");
        jButton11.setToolTipText("");
        jButton11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 222, 222), 3, true));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        Acercade.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 80, 60));

        jButton12.setBackground(new java.awt.Color(60, 64, 67));
        jButton12.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(74, 222, 222));
        jButton12.setText("6");
        jButton12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 222, 222), 3, true));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        Acercade.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 80, 60));

        jButton14.setBackground(new java.awt.Color(60, 64, 67));
        jButton14.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jButton14.setForeground(new java.awt.Color(74, 222, 222));
        jButton14.setText("1");
        jButton14.setToolTipText("");
        jButton14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 222, 222), 3, true));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        Acercade.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 80, 60));

        jButton15.setBackground(new java.awt.Color(60, 64, 67));
        jButton15.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jButton15.setForeground(new java.awt.Color(74, 222, 222));
        jButton15.setText("2");
        jButton15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 222, 222), 3, true));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        Acercade.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 80, 60));

        jButton16.setBackground(new java.awt.Color(60, 64, 67));
        jButton16.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jButton16.setForeground(new java.awt.Color(74, 222, 222));
        jButton16.setText("3");
        jButton16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 222, 222), 3, true));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        Acercade.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 80, 60));

        jButton19.setBackground(new java.awt.Color(60, 64, 67));
        jButton19.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jButton19.setForeground(new java.awt.Color(74, 222, 222));
        jButton19.setText("0");
        jButton19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(74, 222, 222), 3, true));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        Acercade.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 260, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Acercade, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Acercade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimHexDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimHexDecActionPerformed
        // TODO add your handling code here
         txtHexDec.setText("");
        txtResHexDec.setText("");
    }//GEN-LAST:event_btnLimHexDecActionPerformed

    private void btnConvHexDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvHexDecActionPerformed
        // TODO add your handling code here:
        ConvHexadecimalDecimal();
    }//GEN-LAST:event_btnConvHexDecActionPerformed

    private void txtResHexDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResHexDecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResHexDecActionPerformed

    private void txtHexDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHexDecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHexDecActionPerformed

    private void txtDecBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDecBinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDecBinActionPerformed

    private void txtResDecBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResDecBinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResDecBinActionPerformed

    private void btbConvDecBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbConvDecBinActionPerformed
        // TODO add your handling code here:
        ConvDecimalBinario();
    }//GEN-LAST:event_btbConvDecBinActionPerformed

    private void btnLimDecBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimDecBinActionPerformed
        txtDecBin.setText("");
        txtResDecBin.setText("");
    }//GEN-LAST:event_btnLimDecBinActionPerformed

    private void txtDecHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDecHexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDecHexActionPerformed

    private void txtResDecHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResDecHexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResDecHexActionPerformed

    private void btnConvDecHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvDecHexActionPerformed
        // TODO add your handling code here:
        ConvDecimalHexadecimal();
    }//GEN-LAST:event_btnConvDecHexActionPerformed

    private void btnLimDecHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimDecHexActionPerformed
        // TODO add your handling code here:
         txtDecHex.setText("");
        txtResDecHex.setText("");
    }//GEN-LAST:event_btnLimDecHexActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        jLabel1.setText(jLabel1.getText()+"0");
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
          jLabel1.setText(jLabel1.getText()+"1");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
          jLabel1.setText(jLabel1.getText()+"2");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
          jLabel1.setText(jLabel1.getText()+"3");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
          jLabel1.setText(jLabel1.getText()+"4");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
          jLabel1.setText(jLabel1.getText()+"5");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
          jLabel1.setText(jLabel1.getText()+"6");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
          jLabel1.setText(jLabel1.getText()+"7");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
          jLabel1.setText(jLabel1.getText()+"8");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
          jLabel1.setText(jLabel1.getText()+"9");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        numerouno = Integer.parseInt(jLabel1.getText());
        signo ="/";
        jLabel1.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        numerouno = Integer.parseInt(jLabel1.getText());
        signo ="*";
        jLabel1.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        numerouno = Integer.parseInt(jLabel1.getText());
        signo ="-";
        jLabel1.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        numerouno = Integer.parseInt(jLabel1.getText());
        signo ="+";
        jLabel1.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        numerodos = Integer.parseInt(jLabel1.getText());
        
        switch(signo){
            case "+":
                jLabel1.setText(Integer.toString(numerouno+numerodos));
                break;
            case "-":
                jLabel1.setText(Integer.toString(numerouno-numerodos));
                break;
            case "*":
                jLabel1.setText(Integer.toString(numerouno*numerodos));
                break;
            case "/":
                jLabel1.setText(Integer.toString(numerouno/numerodos));
                break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void tema() {

        java.awt.EventQueue.invokeLater(() -> {
           try {
             
                   UIManager.setLookAndFeel(new FlatIntelliJLaf());
               
               new ConversorUnidades().setVisible(true);
               
           } catch(UnsupportedLookAndFeelException ex){
               Logger.getLogger(ConversorUnidades.class.getName()).log(Level.SEVERE, null, ex);
          
           }
           

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Acercade;
    private javax.swing.JButton btbConvDecBin;
    private javax.swing.JButton btnConvDecHex;
    private javax.swing.JButton btnConvHexDec;
    private javax.swing.JButton btnLimDecBin;
    private javax.swing.JButton btnLimDecHex;
    private javax.swing.JButton btnLimHexDec;
    private javax.swing.JPanel etiuno;
    private javax.swing.JPanel etiuno1;
    private javax.swing.JPanel etiuno2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JTextField txtDecBin;
    private javax.swing.JTextField txtDecHex;
    private javax.swing.JTextField txtHexDec;
    private javax.swing.JTextField txtResDecBin;
    private javax.swing.JTextField txtResDecHex;
    private javax.swing.JTextField txtResHexDec;
    // End of variables declaration//GEN-END:variables
}
