
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 14 16:16:27 CDT 2022
//----------------------------------------------------

package ensambladoresproyecto3;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
    
  public static final int dw = 3;
  public static final int Pseudo_const_hexa = 9;
  public static final int Pseudo_const_num = 5;
  public static final int Pseudo_const_carac = 13;
  public static final int ERROR = 7;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Pseudo_const_bin = 11;
  public static final int Const_carac = 8;
  public static final int Numero = 10;
  public static final int Simbolo = 6;
  public static final int Num_exa = 4;
  public static final int Pseudoinstruccion = 2;
  public static final int db = 12;
}

